version: '3'

services:
    splinterlandsbotv2:
        restart: unless-stopped
        container_name: splinterlands
        build: .
        volumes:
            - ./config:/bot/config
        command: ["dotnet", "/bot/Ultimate Splinterlands Bot V2.dll"]